import classes from "./Login.module.scss";
import Head from "next/head";

const Login = () => {
  return (
    <>
      <Head>
        <title>ASG Chat App | Login</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className={classes.login}>
          <div className={classes.container}>
            <h1>ASG Chat App</h1>
            <form>
              <input
                type="text"
                placeholder="Username"
                className={`input--light`}
              />
              <input 
                type="password" 
                placeholder="Password" 
                className={`input--light`}
              />
              <button type="submit" className={`${classes.btn} btn btn--dark`}>
                LOG IN
              </button>
            </form>
          </div>
        </div>
      </main>
    </>
  );
};

export default Login;
