import classes from "./Login.module.scss";
import Head from "next/head";
import axios from "axios";
import { useEffect, useState } from "react";
import { loginRoute } from "../api/APIRoutes";
import Link from "next/link";
import { useRouter } from "next/router";

const Login = () => {
  const [values, setValues] = useState({
    username: "",
    password: ""
  });

  const [initRender, setInitRender] = useState(true);

  const router = useRouter();
  // const pathname = router.pathname;

  const submitHandler = (e) => {
    e.preventDefault();

    setValues({
      username: e.target[0].value,
      password: e.target[1].value
    });
  }

  useEffect(() => {
    if (initRender) {
      if (localStorage.getItem("chat-app-user")) {
        router.push('/');
      }

      setInitRender(false);
    }

    if (!initRender) {
      const loginAccount = async () => {
        const {username, password} = values;
        
        const {data} = await axios.post(loginRoute, {
          username,
          password
        });


        if (data.status === false) {
          console.log(data.msg);
        }

        if (data.status === true) {
          localStorage.setItem("chat-app-user", JSON.stringify(data.user));
          router.push('/');
        }
      }

      loginAccount();
    }
  }, [values]);

  return (
    <>
      <Head>
        <title>ASG Chat App | Login</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className={classes.login}>
          <div className={classes.container}>
            <h1>ASG Chat App</h1>
            <form onSubmit={submitHandler}>
              <input
                type="text"
                placeholder="Username"
                className={`input--light`}
                min="3"
              />
              <input 
                type="password" 
                placeholder="Password" 
                className={`input--light`}
              />
              <button type="submit" className={`${classes.btn} btn btn--dark`}>
                Log in
              </button>
            </form>
            <p className={classes.signup}>Don&apos;t have an account? <Link href={{pathname:`/register`}}><span>Sign up</span></Link></p>
          </div>
        </div>
      </main>
    </>
  );
};

export default Login;
