import classes from "./Register.module.scss";
import Head from "next/head";
import axios from "axios";
import { useState } from "react";
import { registerRoute } from "../api/APIRoutes";

const Register = () => {  
  const [values, setValues] = useState({
    username: "",
    password: "",
    confirmPassword: ""
  });

  console.log(values);

  const changeHandler = (e) => {
    console.log("test");
    setValues({ ...values, [e.target.name]: e.target.value});
  }

  const submitHandler = async(e) => {
    e.preventDefault(); 
    
    console.log("in validation", registerRoute);
    const {username, password, confirmPassword} = values;
    const {data} = await axios.post(registerRoute, {
      username, password, confirmPassword
    });
  }

  return (
    <>
      <Head>
        <title>ASG Chat App | Create Account</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className={classes.register}>
          <div className={classes.container}>
            <h1>ASG Chat App</h1>
            <form onSubmit={submitHandler}>
              <input
                type="text"
                placeholder="Username"
                className={`input--light`}
                onChange={changeHandler}
              />
              <input 
                type="password" 
                placeholder="Password" 
                className={`input--light`}
                onChange={changeHandler}
              />
              <input 
                type="password" 
                placeholder="Confirm Password" 
                className={`input--light`}
                onChange={changeHandler}
              />
              <button type="submit" className={`${classes.btn} btn btn--dark`}>
                Create Account
              </button>
            </form>
          </div>
        </div>
      </main>
    </>
  );
};

export default Register;
