import classes from "./Register.module.scss";
import Head from "next/head";
import axios from "axios";
import { useEffect, useState } from "react";
import { registerRoute } from "../api/APIRoutes";

const Register = () => {
  const [values, setValues] = useState({
    username: "",
    password: "",
    confirmPassword: "",
  });

  // const changeHandler = (event) => {
  //   setValues({ ...values, [event.target.name]: event.target.value });
  // }

  // const submitHandler = async(e) => {
  //   e.preventDefault();

  //   console.log("in validation", registerRoute);
  //   const {username, password, confirmPassword} = values;
  //   const {data} = await axios.post(registerRoute, {
  //     username, password, confirmPassword
  //   });
  // }

  const submitHandler = (e) => {
    e.preventDefault();

    console.log(e.target[0].value);
    setValues({
      username: e.target[0].value,
      password: e.target[1].value,
      confirmPassword: e.target[2].value,
    });
  };

  useEffect(() => {
    const registerData = async () => {
      const { username, password, confirmPassword } = values;
      const { data } = await axios.post(registerRoute, {
        username,
        password,
        confirmPassword,
      });
    };

    registerData();
  }, [values]);

  return (
    <>
      <Head>
        <title>ASG Chat App | Create Account</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className={classes.register}>
          <div className={classes.container}>
            <h1>ASG Chat App</h1>
            <form onSubmit={submitHandler}>
              <input
                type="text"
                placeholder="Username"
                className={`input--light`}
                // onChange={(e) => changeHandler(e)}
                // onChange={changeHandler}
              />
              <input
                type="password"
                placeholder="Password"
                className={`input--light`}
                // onChange={(e) => changeHandler(e)}
                // onChange={changeHandler}
              />
              <input
                type="password"
                placeholder="Confirm Password"
                className={`input--light`}
                // onChange={(e) => changeHandler(e)}
                // onChange={changeHandler}
              />
              <button type="submit" className={`${classes.btn} btn btn--dark`}>
                Create Account
              </button>
            </form>
          </div>
        </div>
      </main>
    </>
  );
};

export default Register;
